### ISSUE TITLE
文字审核是有字数限制的。

### ISSUE THREAD

**Issue by gyp719** [overtrue/laravel-qcs#10]
文字审核是有字数限制的， 超过字数限时是会提示错误的， 是否可以对字符进行切割，分块处理？

![image](https://user-images.githubusercontent.com/30563368/222035408-9b897919-07d6-44ba-8687-a54c978effd0.png)

**Comment by overtrue** [comment]
其实模型 trait 里是这么做的，但是从职责方面考虑，单独的检测函数没有默认做分段处理，你看看参考这里写一下？

https://github.com/overtrue/laravel-qcloud-content-audit/blob/master/src/Traits/CheckTextWithTms.php#L32-L41

**Comment by gyp719** [comment]
> 其实模型 trait 里是这么做的，但是从职责方面考虑，单独的检测函数没有默认做分段处理，你看看参考这里写一下？
> 
> https://github.com/overtrue/laravel-qcloud-content-audit/blob/master/src/Traits/CheckTextWithTms.php#L32-L41

好的， 谢谢。
